AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'SAM template for Serverless framework service: '
Resources:
  Hello:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.serverless.Handler
      Runtime: java8
      CodeUri: build/libs/kws-api-dev-all.jar
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables: {}
      Events:
        Event1:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId:
              Ref: KwsApi
  KwsApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: dev
      DefinitionBody:
        swagger: '2.0'
        info:
          title:
            Ref: 'AWS::StackName'
        paths:
          /hello:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  'Fn::Sub': >-
                    arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Hello.Arn}/invocations
              responses: {}
          /reservations:
            options:
              x-amazon-apigateway-integration:
                type: mock
                requestTemplates:
                  application/json: '{ "statusCode" : 200 }'
                responses:
                  default:
                    statusCode: 200
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key'''
                      method.response.header.Access-Control-Allow-Methods: '''get'''
                      method.response.header.Access-Control-Allow-Origin: '''*'''
                    responseTemplates:
                      application/json: '{}'
              responses:
                '200':
                  headers:
                    Access-Control-Allow-Headers:
                      type: string
                    Access-Control-Allow-Methods:
                      type: string
                    Access-Control-Allow-Origin:
                      type: string
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  'Fn::Sub': >-
                    arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetReservationListHandler.Arn}/invocations
                responses:
                  default:
                    statusCode: 200
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key'''
                      method.response.header.Access-Control-Allow-Methods: '''get'''
                      method.response.header.Access-Control-Allow-Origin: '''*'''
                    responseTemplates:
                      application/json: '{}'
              responses:
                '200':
                  headers:
                    Access-Control-Allow-Headers:
                      type: string
                    Access-Control-Allow-Methods:
                      type: string
                    Access-Control-Allow-Origin:
                      type: string
          '/tables/{time}':
            options:
              x-amazon-apigateway-integration:
                type: mock
                requestTemplates:
                  application/json: '{ "statusCode" : 200 }'
                responses:
                  default:
                    statusCode: 200
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key'''
                      method.response.header.Access-Control-Allow-Methods: '''get'''
                      method.response.header.Access-Control-Allow-Origin: '''*'''
                    responseTemplates:
                      application/json: '{}'
              responses:
                '200':
                  headers:
                    Access-Control-Allow-Headers:
                      type: string
                    Access-Control-Allow-Methods:
                      type: string
                    Access-Control-Allow-Origin:
                      type: string
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  'Fn::Sub': >-
                    arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetTableListHandler.Arn}/invocations
                responses:
                  default:
                    statusCode: 200
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key'''
                      method.response.header.Access-Control-Allow-Methods: '''get'''
                      method.response.header.Access-Control-Allow-Origin: '''*'''
                    responseTemplates:
                      application/json: '{}'
              responses:
                '200':
                  headers:
                    Access-Control-Allow-Headers:
                      type: string
                    Access-Control-Allow-Methods:
                      type: string
                    Access-Control-Allow-Origin:
                      type: string
  HelloLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    DependsOn:
      - Hello
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        Ref: Hello
      Principal: apigateway.amazonaws.com
  GetReservationListHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.serverless.handlers.GetReservationListHandler
      Runtime: java8
      CodeUri: build/libs/kws-api-dev-all.jar
      MemorySize: 128
      Timeout: 100
      Environment:
        Variables: {}
      Events:
        Event1:
          Type: Api
          Properties:
            Path: /reservations
            Method: get
            RestApiId:
              Ref: KwsApi
  GetReservationListHandlerLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    DependsOn:
      - GetReservationListHandler
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        Ref: GetReservationListHandler
      Principal: apigateway.amazonaws.com
  GetTableListHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.serverless.handlers.GetTableListHandler
      Runtime: java8
      CodeUri: build/libs/kws-api-dev-all.jar
      MemorySize: 128
      Timeout: 100
      Environment:
        Variables: {}
      Events:
        Event1:
          Type: Api
          Properties:
            Path: '/tables/{time}'
            Method: get
            RestApiId:
              Ref: KwsApi
  GetTableListHandlerLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    DependsOn:
      - GetTableListHandler
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        Ref: GetTableListHandler
      Principal: apigateway.amazonaws.com
